### ISSUE TITLE
JupyterRenderer returns JavaScript error

### ISSUE THREAD

**Issue by MarAlder** [DLR-SL/CPACS_Seminar#7]
Installing pythreejs and running this test notebook [occRenderer_test.ipynb](https://github.com/DLR-SL/CPACS_Seminar/blob/aa9fba03bae78539b4e26528a2a774ae8de19a5e/Notebooks/Tigl_Basic/occRenderer_test.ipynb) returns a JavaScript error:

![grafik](https://user-images.githubusercontent.com/43143741/233575080-deff3168-f8d5-4b84-a7e1-9685165a3835.png)

Expected output: [TiGL Seminar slides](https://elib.dlr.de/124425/3/Python%20API-Customization-Visualization.pdf)
![grafik](https://user-images.githubusercontent.com/43143741/233589448-c3f2cb52-e385-4043-84ef-bab03c2d24b6.png)

**Comment by joergbrech** [comment]
This is probably related to https://github.com/jupyter-widgets/pythreejs/issues/389

**Comment by MarAlder** [comment]
Thanks for the link, @joergbrech. I found a working config with:

```
  - python=3.10
  - numpy
  - tixi3
  - tigl3
  - pythreejs=2.4.2
  - jupyter
  - ipydatawidgets=4.3.2
  - ipykernel=6.21.2
  - ipython=8.12.0 
  - ipywidgets=7.7.2
  - jupyter=1.0.0
  - jupyterlab=3.6.1
  - jupyterlab_widgets=1.1.1
  - notebook=6.5.2
```

![grafik](https://user-images.githubusercontent.com/43143741/234220264-0d9a6804-a656-4055-a1e9-b357a1873055.png)
